# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

################################################################################

API_VERSION=2
CURRENT_DIR="#{File.dirname(__FILE__)}"

################################################################################

yaml_config = YAML.load_file('config.yml')
vms         = yaml_config["vms"]

################################################################################

module OS
    def OS.windows?
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end

    def OS.mac?
        (/darwin/ =~ RUBY_PLATFORM) != nil
    end

    def OS.unix?
        !OS.windows?
    end

    def OS.linux?
        OS.unix? and not OS.mac?
    end
end

Vagrant.configure(API_VERSION) do |config|
  vms.each do |vm_host, vm_conf|

    config.vm.define vm_host, autostart: true do |conf|
      conf.ssh.forward_agent = true
      conf.ssh.insert_key = false

      conf.vm.box = vm_conf["box"]
      if !(vm_conf["box_url"].nil?)
        conf.vm.box_url = vm_conf["box_url"]
      end

      if !(vm_conf["box_download_checksum"].nil?)
        conf.vm.box_download_checksum = vm_conf["box_download_checksum"]
        conf.vm.box_download_checksum_type = "sha1"
        conf.vm.box_check_update = false
      end

      conf.vm.hostname = "#{vm_host}"

      if !(vm_conf["ip"].nil?)
        conf.vm.network "private_network", ip: vm_conf["ip"]
      end

      conf.vm.provider "virtualbox" do |vbox|
        vbox.memory = vm_conf["memory"] || 512
        vbox.cpus   = vm_conf["cpus"] || 1
      end

    end
  end
end

################################################################################
