.\" Manpage for vgrepo.
.\" Contact inbox@gongled.ru to correct errors or typos.

.TH man 1 "02 May 2017" "1.0.0" "vgrepo man page"

.SH NAME
vgrepo \- utility for operating Vagrant images

.SH SYNOPSIS
vgrepo [USERNAME]

.SH DESCRIPTION
vgrepo is a tool for adding, listing and deleting Vagrant images from the repositories.

.SH OPTIONS
The vgrepo does not take any options.

.SH BUGS
No known bugs.

.SH AUTHOR
Gleb Goncharov (inbox@gongled.ru)